services:
  redis:
    image: 'redis'
    command: [ "redis-server", "--bind", "redis", "--port", "6379" ]
    ports:
      - '6379:6379'
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: building_predictor
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
  backend:
    command:
      - /bin/sh
      - -c
      - sleep 1; npm run migration:run; node main.js
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      DB_NAME: building_predictor
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

    depends_on:
      - postgres
    image: banzai/predictor-gateway:v0.0.1
    build:
      context: backend/predictor-gateway
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  ml:
    image: banzai/predictor-ml:v0.0.1
    build:
      context: ml
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
volumes:
  app: