apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: {{.Release.Namespace}}
spec:
  generators:
    - git:
        repoURL: {{ .Values.gitRepo }}
        revision: HEAD
        directories:
          - path: "k8s-apps"
  template:
    metadata:
      name: '{{print "{{path.basename}}"}}'
    spec:
      project: "default"
      syncPolicy:
        automated: { }
        syncOptions:
          - CreateNamespace=true
      source:
        repoURL: {{ .Values.gitRepo }}
        targetRevision: HEAD
        path: k8s-apps/'{{print "{{path}}"}}'
        helm:
          valueFiles:
            - values.yaml
            - values-{{ .Values.env }}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{print "{{path.basename}}"}}'
