#rabbitmq:
#  auth:
#

rabbitmq:
  livenessProbe:
    enabled: true
    initialDelaySeconds: 120
    timeoutSeconds: 20
    periodSeconds: 30
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    timeoutSeconds: 20
    periodSeconds: 30
    failureThreshold: 3
    successThreshold: 1
  nodeSelector:
    target: apps

  tolerations:
    - key: "target"
      operator: "Equal"
      value: "apps"
      effect: "NoSchedule"