gitRepo: git@github.com:banzai-team/prediction.git
env: production

argo-cd:
  configs:
    cm:
      admin.enabled: true
      url: http://argocd.ewolke.io
    params:
      server.insecure: true
#    rbac:
#      policy.default: role:org-admin
#      policy.csv: |
#        p, role:org-admin, applications, *, */*, allow
#        p, role:org-admin, certificates, *, *, allow
#        p, role:org-admin, clusters, *, *, allow
#        p, role:org-admin, repositories, *, *, allow
#        p, role:org-admin, projects, *, *, allow
#        p, role:org-admin, accounts, update, *, allow
#        p, role:org-admin, gpgkeys, *, *, allow
#
#        p, role:org-dev, applications, *, */*, allow
#        p, role:org-dev, certificates, create, *, allow
#        p, role:org-dev, certificates, update, *, allow
#        p, role:org-dev, repositories, create, *, allow
#        p, role:org-dev, repositories, update, *, allow
#        p, role:org-dev, repositories, delete, *, allow
#        p, role:org-dev, projects, create, *, allow
#        p, role:org-dev, projects, update, *, allow
#        p, role:org-dev, gpgkeys, create, *, allow

    repositories:
#      yandex:
#        enableOCI: "true"
#        name: cr.yandex
#        password: "test"
#        type: helm
#        url: cr.yandex
#        username: json_key
#  helm pull oci://cr.yandex/yc-marketplace/yandex-cloud/yc-alb-ingress/yc-alb-ingress-controller-chart --version v0.1.13
#  server:
#    ingress:
#      enabled: true
#      annotations:
#        kubernetes.io/ingress.class: nginx
#      hosts:
#        - argocd.ewolke.io
