redis:
  metrics:
    enabled: true
  master:
    tolerations:
      - key: "target"
        operator: "Equal"
        value: "apps"
        effect: "NoSchedule"
    nodeSelector:
      target: apps
  requests:
    cpu: 1.0
    memory: 2Gi
  architecture: standalone
  auth:
    password: RTKIOQcibQ
